### ISSUE TITLE
Emails Not Working

### ISSUE THREAD

**Issue by mrmonteith** [mongoose-os-apps/aws-iot-button#1]
I tried this and it all works except the emails.  I get email that I have to click on to confirm receiving notifications and it's successful.  However I never receive any more notifications.  You go over to Amazon to open a case and they want $29+ a month to fix the issue.   I'm just letting you know as I know I can't be the only one.  I found no solution over there.   If you have some sort of working relationship with Amazon they need to address this.  I've tried a couple of email addresses and the same thing. You get the confirmation email, you click on it and it's successful, but no more emails after that when you press the button.   It's not your fault but might address this with them.   But it also doesn't help foster the use of this tutorial if it's not going to work in the end.   I'd love to see it work.

**Comment by mrmonteith** [comment]
I turned on logging and get EVENT:MQTT Client Connect MESSAGE:Connect Status: AUTHORIZATION_ERROR.   Doesn't help much as I followed all the steps.

**Comment by ahollyer** [comment]
I had the exact same problem. The AWS IoT Rule is misconfigured. Resolved it with the following steps:

1. Log into your AWS console at https://aws.amazon.com
2. Go to the AWS IoT service
3. Click "Act" in the lefthand menu, a Rules dashboard comes up
4. Click the card for the rule that matches your device
5. Next to the "Rule Query Statement" heading, click edit
6. Go to topic filter. Change it to the actual topic name your device is publishing to: YOUR_DEVICE_NAME/button_pressed
